import { SideBar } from "@/components/";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Online Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex text-[#112D4E] h-screen overflow-y-scroll ">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
